//
//  Uniforms.h
//  Assignment2
//
//  Created by Shane Spoor on 2015-03-04.
//  Copyright (c) 2015 BCIT. All rights reserved.
//

#ifndef Assignment2_Uniforms_h
#define Assignment2_Uniforms_h

enum
{
    UNIFORM_MODELVIEW_MATRIX,
    UNIFORM_PROJECTION_MATRIX,
    UNIFORM_NORMAL_MATRIX,
    UNIFORM_TEXTURE,
    UNIFORM_LIGHT_POSITION,
    UNIFORM_LIGHT_ON,
    UNIFORM_LIGHT_DIRECTION,
    UNIFORM_LIGHT_INTENSITY,
    UNIFORM_LIGHT_CONE_ANGLE_COSINE,
    UNIFORM_LIGHT_COLOUR,
    UNIFORM_AMBIENT,
    UNIFORM_SPECULAR,
    UNIFORM_SHININESS,
    UNIFORM_FOG_COLOUR,
    UNIFORM_FOG_TYPE,
    UNIFORM_FOG_DENSITY,
    UNIFORM_FOG_START,
    UNIFORM_FOG_END,
    NUM_UNIFORMS
};

#endif
